-- MySQL Script generated by MySQL Workbench
-- Tue Aug 23 23:58:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 71nd3r
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 71nd3r
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `71nd3r` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `71nd3r` ;

-- -----------------------------------------------------
-- Table `71nd3r`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `71nd3r`.`Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Accounts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fb_email` VARCHAR(90) NOT NULL,
  `fb_password` VARCHAR(45) NOT NULL,
  `fb_id` VARCHAR(90) NOT NULL,
  `fb_token` VARCHAR(255) NULL,
  `tinder_token` VARCHAR(255) NULL,
  `last_activity_date` DATETIME NULL,
  `like_reminings` INT UNSIGNED NULL,
  `superlike_reminings` TINYINT UNSIGNED NULL,
  `superlike_reset_at` DATETIME NULL,
  `bio` TEXT NULL,
  `age_filter_min` TINYINT UNSIGNED NULL,
  `age_filter_max` TINYINT UNSIGNED NULL,
  `gender` TINYINT UNSIGNED NULL,
  `distance_filter` TINYINT UNSIGNED NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `gender_pref` SMALLINT UNSIGNED NULL,
  `loc_long` VARCHAR(45) NULL,
  `loc_lat` VARCHAR(45) NULL,
  `loc_name` VARCHAR(45) NULL,
  `refresh_rate` INT NULL,
  `refresh_set` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`fb_email` ASC),
  UNIQUE INDEX `fbid_UNIQUE` (`fb_id` ASC),
  INDEX `fk_Accounts_Users_idx` (`user_id` ASC),
  CONSTRAINT `fk_Accounts_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `71nd3r`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `71nd3r`.`Persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `_id` VARCHAR(90) NOT NULL,
  `bio` TEXT NOT NULL,
  `photos` TEXT NOT NULL,
  `instagram` TEXT NULL,
  `birth_date` DATETIME NOT NULL,
  `ping_time` DATETIME NOT NULL,
  `datetime` DATETIME NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  `Girlscol` VARCHAR(45) NULL,
  `gender` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `71nd3r`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `sent_date` DATETIME NOT NULL,
  `girl_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Messages_Girls1_idx` (`girl_id` ASC),
  INDEX `fk_Messages_Accounts1_idx` (`account_id` ASC),
  CONSTRAINT `fk_Messages_Girls1`
    FOREIGN KEY (`girl_id`)
    REFERENCES `71nd3r`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Messages_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `71nd3r`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `71nd3r`.`Actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Actions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `like` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `superlike` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `pass` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `match` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `match_id` VARCHAR(90) NULL,
  `account_id` INT UNSIGNED NOT NULL,
  `girl_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Actions_Accounts1_idx` (`account_id` ASC),
  INDEX `fk_Actions_Girls1_idx` (`girl_id` ASC),
  CONSTRAINT `fk_Actions_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `71nd3r`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actions_Girls1`
    FOREIGN KEY (`girl_id`)
    REFERENCES `71nd3r`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `71nd3r`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `71nd3r`.`Photos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `_id` VARCHAR(90) NULL,
  `fb_id` VARCHAR(90) NULL,
  `order` TINYINT NULL,
  `url` VARCHAR(90) NULL,
  `account_id` INT UNSIGNED NULL,
  `person_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Photos_Accounts1_idx` (`account_id` ASC),
  INDEX `fk_Photos_Persons1_idx` (`person_id` ASC),
  CONSTRAINT `fk_Photos_Accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `71nd3r`.`Accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Photos_Persons1`
    FOREIGN KEY (`person_id`)
    REFERENCES `71nd3r`.`Persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
